-- ============================================================================
-- BENCHMARK MMS — MATERIAL ALIASES FOR OCR & INTELLIGENT MATCHING
-- Maps OCR recognition variants, misspellings, and vendor-specific naming
-- to Canonical Material Master records.
-- ============================================================================

CREATE TABLE IF NOT EXISTS material_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias_pattern TEXT NOT NULL UNIQUE,
    canonical_text TEXT NOT NULL,
    material_code TEXT,
    category TEXT,
    confidence_boost NUMERIC(3, 2) NOT NULL DEFAULT 0.95,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_material_aliases_pattern ON material_aliases(LOWER(alias_pattern));
CREATE INDEX IF NOT EXISTS idx_material_aliases_code ON material_aliases(material_code);

-- Seed proven vendor & OCR recognition patterns
INSERT INTO material_aliases (alias_pattern, canonical_text, material_code, category, confidence_boost)
VALUES
    ('BUTTEFLY', 'BUTTERFLY', NULL, 'TEA', 0.98),
    ('KOSHERKING NAPKIN', 'KOSHER KING NAPKIN', '900', 'PACKAGING', 0.98),
    ('WOODENSPOONSMALL', 'WOODEN SPOON SMALL', '901', 'PACKAGING', 0.98),
    ('WOODENSPOON', 'WOODEN SPOON', '901', 'PACKAGING', 0.95),
    ('PETJAR', 'PET JAR', '902', 'PACKAGING', 0.95),
    ('LDCOVER', 'LD COVER', '903', 'PACKAGING', 0.95),
    ('4LDCOVER', 'LD COVER', '903', 'PACKAGING', 0.95),
    ('ST.POUCH', 'ST. POUCH', '904', 'PACKAGING', 0.95),
    ('ST.POUCH BROWN', 'ST. POUCH BROWN', '904', 'PACKAGING', 0.98),
    ('COLLO TAPE', 'CELLO TAPE', '905', 'PACKAGING', 0.98),
    ('CELLOTAPE', 'CELLO TAPE', '905', 'PACKAGING', 0.98),
    ('COLLO', 'CELLO', '905', 'PACKAGING', 0.90),
    ('PAPERSTRAW', 'PAPER STRAW', '908', 'PACKAGING', 0.95),
    ('9PAPER', 'PAPER', NULL, 'PACKAGING', 0.90),
    ('RIPPLETUMBLER', 'RIPPLE TUMBLER', '910', 'PACKAGING', 0.95),
    ('ROWN TAPE', 'BROWN TAPE', '907', 'PACKAGING', 0.95),
    ('PET JAR - 600ML', 'PET JAR - 500ML', '902', 'PACKAGING', 0.90)
ON CONFLICT (alias_pattern) DO NOTHING;
