-- ============================================================================
-- BENCHMARK MMS — PRODUCTION SYSTEM MIGRATION
-- 1. Idempotency Keys & Duplicate Prevention
-- 2. User Profiles, Roles & Granular Permissions
-- 3. Notifications & Realtime Inventory Alerts
-- 4. Audit Logging
-- 5. Updated Transaction RPCs with Idempotency Support
-- 6. Realtime Publications
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. IDEMPOTENCY KEYS TABLE
-- Prevents duplicate transactions across invoices, transfers, dispatches, adjustments
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS idempotency_keys (
    idempotency_key TEXT PRIMARY KEY,
    operation_type TEXT NOT NULL,
    user_id UUID,
    device_id TEXT,
    status TEXT NOT NULL DEFAULT 'completed',
    response JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_idempotency_keys_type ON idempotency_keys(operation_type);
CREATE INDEX IF NOT EXISTS idx_idempotency_keys_created ON idempotency_keys(created_at);

-- ----------------------------------------------------------------------------
-- 2. USER PROFILES & PERMISSIONS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username TEXT UNIQUE,
    full_name TEXT,
    role TEXT NOT NULL DEFAULT 'STAFF' CHECK (role IN ('ADMIN', 'MANAGER', 'STAFF', 'VIEWER')),
    permissions TEXT[] NOT NULL DEFAULT '{}',
    device_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_profiles_username ON user_profiles(username);
CREATE INDEX IF NOT EXISTS idx_user_profiles_role ON user_profiles(role);

-- Seed profile for user 'bm'
INSERT INTO user_profiles (id, username, full_name, role, permissions)
SELECT 
    id,
    'bm',
    'Benchmark Manager',
    'ADMIN',
    ARRAY[
        'materials.view', 'materials.create', 'materials.edit', 'materials.delete',
        'invoice.view', 'invoice.create', 'invoice.edit', 'invoice.delete',
        'transfer.view', 'transfer.create', 'transfer.edit', 'transfer.delete',
        'dispatch.view', 'dispatch.create', 'dispatch.edit', 'dispatch.delete',
        'stock_adjustment.view', 'stock_adjustment.create',
        'reports.view', 'reports.export',
        'users.manage', 'settings.manage'
    ]
FROM auth.users
WHERE email = 'bm@benchmarkmms.com'
ON CONFLICT (id) DO UPDATE SET
    role = 'ADMIN',
    permissions = EXCLUDED.permissions,
    updated_at = CURRENT_TIMESTAMP;

-- Seed profile for existing users if any
INSERT INTO user_profiles (id, username, full_name, role, permissions)
SELECT 
    id,
    split_part(email, '@', 1),
    COALESCE(raw_user_meta_data->>'full_name', split_part(email, '@', 1)),
    'ADMIN',
    ARRAY[
        'materials.view', 'materials.create', 'materials.edit', 'materials.delete',
        'invoice.view', 'invoice.create', 'invoice.edit', 'invoice.delete',
        'transfer.view', 'transfer.create', 'transfer.edit', 'transfer.delete',
        'dispatch.view', 'dispatch.create', 'dispatch.edit', 'dispatch.delete',
        'stock_adjustment.view', 'stock_adjustment.create',
        'reports.view', 'reports.export',
        'users.manage', 'settings.manage'
    ]
FROM auth.users
WHERE email IN ('owner@benchmarkmms.com', 'admin@benchmarkmms.com')
ON CONFLICT (id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- 3. AUDIT LOGS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,
    user_email TEXT,
    device_id TEXT,
    operation TEXT NOT NULL,
    module TEXT NOT NULL,
    record_id TEXT,
    details JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_module ON audit_logs(module);

-- ----------------------------------------------------------------------------
-- 4. NOTIFICATIONS TABLE
-- Real-time notification & alert system for low stock, reorder, expiry, out of stock
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    type TEXT NOT NULL, -- 'reorder', 'out_of_stock', 'low_stock', 'expiring', 'expired', 'system'
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    severity TEXT NOT NULL CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL')),
    reference_type TEXT, -- 'material', 'batch', 'invoice', 'transfer', 'dispatch'
    reference_id TEXT,
    is_read BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_unread ON notifications(user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_created ON notifications(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_ref ON notifications(reference_type, reference_id);

-- ----------------------------------------------------------------------------
-- 5. AUTOMATIC ALERT GENERATION FUNCTION
-- Dynamically checks inventory thresholds and raises notifications
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION generate_inventory_alerts()
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_rec RECORD;
    v_alert_count INT := 0;
    v_existing_id BIGINT;
BEGIN
    -- 1. OUT OF STOCK ALERTS (quantity <= 0)
    FOR v_rec IN
        SELECT material_code, description, quantity, unit
        FROM materials
        WHERE quantity <= 0
    LOOP
        SELECT id INTO v_existing_id
        FROM notifications
        WHERE reference_type = 'material'
          AND reference_id = v_rec.material_code
          AND type = 'out_of_stock'
          AND is_read = false
        LIMIT 1;

        IF v_existing_id IS NULL THEN
            INSERT INTO notifications (type, title, message, severity, reference_type, reference_id, created_at)
            VALUES (
                'out_of_stock',
                'Out of Stock: ' || v_rec.material_code,
                'Material ' || COALESCE(v_rec.description, v_rec.material_code) || ' is completely out of stock (' || v_rec.quantity || ' ' || v_rec.unit || ').',
                'CRITICAL',
                'material',
                v_rec.material_code,
                CURRENT_TIMESTAMP
            );
            v_alert_count := v_alert_count + 1;
        END IF;
    END LOOP;

    -- 2. REORDER LEVEL ALERTS (quantity <= reorder_level AND quantity > 0)
    FOR v_rec IN
        SELECT material_code, description, quantity, reorder_level, unit
        FROM materials
        WHERE quantity > 0 
          AND reorder_level > 0 
          AND quantity <= reorder_level
    LOOP
        SELECT id INTO v_existing_id
        FROM notifications
        WHERE reference_type = 'material'
          AND reference_id = v_rec.material_code
          AND type = 'reorder'
          AND is_read = false
        LIMIT 1;

        IF v_existing_id IS NULL THEN
            INSERT INTO notifications (type, title, message, severity, reference_type, reference_id, created_at)
            VALUES (
                'reorder',
                'Reorder Level Alert: ' || v_rec.material_code,
                'Material ' || COALESCE(v_rec.description, v_rec.material_code) || ' has reached reorder level. Current: ' || v_rec.quantity || ' ' || v_rec.unit || ' (Reorder threshold: ' || v_rec.reorder_level || ' ' || v_rec.unit || ').',
                'WARNING',
                'material',
                v_rec.material_code,
                CURRENT_TIMESTAMP
            );
            v_alert_count := v_alert_count + 1;
        END IF;
    END LOOP;

    -- 3. LOW STOCK WARNINGS (quantity > reorder_level AND quantity <= reorder_level * 1.25)
    FOR v_rec IN
        SELECT material_code, description, quantity, reorder_level, unit
        FROM materials
        WHERE reorder_level > 0 
          AND quantity > reorder_level 
          AND quantity <= (reorder_level * 1.25)
    LOOP
        SELECT id INTO v_existing_id
        FROM notifications
        WHERE reference_type = 'material'
          AND reference_id = v_rec.material_code
          AND type = 'low_stock'
          AND is_read = false
        LIMIT 1;

        IF v_existing_id IS NULL THEN
            INSERT INTO notifications (type, title, message, severity, reference_type, reference_id, created_at)
            VALUES (
                'low_stock',
                'Low Stock Warning: ' || v_rec.material_code,
                'Material ' || COALESCE(v_rec.description, v_rec.material_code) || ' is approaching reorder level. Current: ' || v_rec.quantity || ' ' || v_rec.unit || '.',
                'INFO',
                'material',
                v_rec.material_code,
                CURRENT_TIMESTAMP
            );
            v_alert_count := v_alert_count + 1;
        END IF;
    END LOOP;

    -- 4. EXPIRED BATCHES & MATERIALS (expiry_date < CURRENT_DATE)
    FOR v_rec IN
        SELECT material_code, description, lot_no, expiry_date, quantity, unit
        FROM materials
        WHERE expiry_date IS NOT NULL 
          AND expiry_date < CURRENT_DATE 
          AND quantity > 0
    LOOP
        SELECT id INTO v_existing_id
        FROM notifications
        WHERE reference_type = 'material'
          AND reference_id = v_rec.material_code
          AND type = 'expired'
          AND is_read = false
        LIMIT 1;

        IF v_existing_id IS NULL THEN
            INSERT INTO notifications (type, title, message, severity, reference_type, reference_id, created_at)
            VALUES (
                'expired',
                'Expired Material: ' || v_rec.material_code,
                'Material ' || COALESCE(v_rec.description, v_rec.material_code) || ' (Lot: ' || COALESCE(v_rec.lot_no, '-') || ') expired on ' || to_char(v_rec.expiry_date, 'YYYY-MM-DD') || ' with ' || v_rec.quantity || ' ' || v_rec.unit || ' remaining!',
                'CRITICAL',
                'material',
                v_rec.material_code,
                CURRENT_TIMESTAMP
            );
            v_alert_count := v_alert_count + 1;
        END IF;
    END LOOP;

    -- 5. EXPIRING SOON (within 30 days)
    FOR v_rec IN
        SELECT material_code, description, lot_no, expiry_date, quantity, unit,
               (expiry_date - CURRENT_DATE) AS days_left
        FROM materials
        WHERE expiry_date IS NOT NULL 
          AND expiry_date >= CURRENT_DATE 
          AND (expiry_date - CURRENT_DATE) <= 30
          AND quantity > 0
    LOOP
        SELECT id INTO v_existing_id
        FROM notifications
        WHERE reference_type = 'material'
          AND reference_id = v_rec.material_code
          AND type = 'expiring'
          AND is_read = false
        LIMIT 1;

        IF v_existing_id IS NULL THEN
            INSERT INTO notifications (type, title, message, severity, reference_type, reference_id, created_at)
            VALUES (
                'expiring',
                'Expiring Soon: ' || v_rec.material_code,
                'Material ' || COALESCE(v_rec.description, v_rec.material_code) || ' (Lot: ' || COALESCE(v_rec.lot_no, '-') || ') will expire in ' || v_rec.days_left || ' days (' || to_char(v_rec.expiry_date, 'YYYY-MM-DD') || ').',
                'WARNING',
                'material',
                v_rec.material_code,
                CURRENT_TIMESTAMP
            );
            v_alert_count := v_alert_count + 1;
        END IF;
    END LOOP;

    RETURN v_alert_count;
END;
$$;

-- ----------------------------------------------------------------------------
-- 6. UPDATED ATOMIC TRANSACTION RPCS WITH IDEMPOTENCY
-- ----------------------------------------------------------------------------

-- 6.1 CREATE PURCHASE WITH IDEMPOTENCY
CREATE OR REPLACE FUNCTION create_purchase(
    p_invoice JSONB,
    p_items JSONB,
    p_idempotency_key TEXT DEFAULT NULL
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_idempotency_key TEXT;
    v_cached_response JSONB;
    v_invoice_id BIGINT;
    v_item RECORD;
    v_gross_amount NUMERIC(15, 2);
    v_discount_amount NUMERIC(15, 2);
    v_net_amount NUMERIC(15, 2);
    v_item_gst NUMERIC(15, 2);
    v_item_igst NUMERIC(15, 2);
    v_item_total NUMERIC(15, 2);
    
    v_calc_subtotal NUMERIC(15, 2) := 0.00;
    v_calc_gst_total NUMERIC(15, 2) := 0.00;
    v_calc_igst_total NUMERIC(15, 2) := 0.00;
    v_final_grand_total NUMERIC(15, 2) := 0.00;
    v_final_total NUMERIC(15, 2) := 0.00;
    
    v_mat_code TEXT;
    v_mat_name TEXT;
    v_category TEXT;
    v_unit TEXT;
    v_hsn_sac TEXT;
    v_grade TEXT;
    v_reorder_level NUMERIC(15, 3);
    v_lot_no TEXT;
    v_p_date DATE;
    v_e_date DATE;
    v_qty NUMERIC(15, 3);
    v_unit_price NUMERIC(15, 2);
    v_disc_pct NUMERIC(5, 2);
    v_gst_pct NUMERIC(5, 2);
    v_igst_pct NUMERIC(5, 2);
    v_batch_no TEXT;
    v_lot_exists BOOLEAN;
    v_result JSONB;
BEGIN
    -- Extract idempotency key from argument or invoice payload
    v_idempotency_key := COALESCE(p_idempotency_key, p_invoice->>'idempotency_key');

    -- Idempotency check: if already processed, return cached response
    IF v_idempotency_key IS NOT NULL AND TRIM(v_idempotency_key) != '' THEN
        SELECT response INTO v_cached_response 
        FROM idempotency_keys 
        WHERE idempotency_key = v_idempotency_key AND status = 'completed';

        IF v_cached_response IS NOT NULL THEN
            RETURN v_cached_response;
        END IF;
    END IF;

    -- Check if invoice_no already exists to prevent duplicate error
    SELECT id INTO v_invoice_id FROM invoices WHERE invoice_no = p_invoice->>'invoice_no';
    IF v_invoice_id IS NOT NULL THEN
        SELECT jsonb_build_object(
            'success', true,
            'invoice_id', id,
            'subtotal', total_excl_tax,
            'total_gst', total_gst,
            'total_igst', total_igst,
            'grand_total', grand_total,
            'final_total', final_total,
            'is_duplicate', true
        ) INTO v_result
        FROM invoices WHERE id = v_invoice_id;
        RETURN v_result;
    END IF;

    -- Insert Invoice Header
    INSERT INTO invoices (
        purchase_id,
        date,
        invoice_no,
        vendor,
        no_of_items,
        total_excl_tax,
        total_gst,
        total_igst,
        cgst_percent,
        sgst_percent,
        round_off_value,
        grand_total,
        final_total,
        payment_status,
        remarks
    ) VALUES (
        p_invoice->>'purchase_id',
        (p_invoice->>'date')::DATE,
        p_invoice->>'invoice_no',
        p_invoice->>'vendor',
        COALESCE((p_invoice->>'no_of_items')::INT, jsonb_array_length(p_items)),
        0, 0, 0,
        COALESCE((p_invoice->>'cgst_percent')::NUMERIC, 0),
        COALESCE((p_invoice->>'sgst_percent')::NUMERIC, 0),
        COALESCE((p_invoice->>'round_off_value')::NUMERIC, 0),
        0, 0,
        COALESCE(p_invoice->>'payment_status', 'Pending'),
        p_invoice->>'remarks'
    ) RETURNING id INTO v_invoice_id;

    -- Process each invoice line item
    FOR v_item IN SELECT * FROM jsonb_to_recordset(p_items) AS x(
        material TEXT,
        description TEXT,
        category TEXT,
        unit TEXT,
        quantity NUMERIC,
        unit_price NUMERIC,
        discount_percentage NUMERIC,
        gst_percentage NUMERIC,
        igst_percentage NUMERIC,
        lot_no TEXT,
        purchase_date TEXT,
        expiry_date TEXT,
        hsn_sac TEXT,
        grade TEXT,
        reorder_level NUMERIC
    )
    LOOP
        v_mat_code := TRIM(v_item.material);
        v_mat_name := TRIM(COALESCE(v_item.description, v_mat_code));
        v_category := TRIM(COALESCE(v_item.category, 'Uncategorized'));
        v_unit := TRIM(COALESCE(v_item.unit, 'kg'));
        v_qty := COALESCE(v_item.quantity, 0);
        v_unit_price := COALESCE(v_item.unit_price, 0);
        v_disc_pct := COALESCE(v_item.discount_percentage, 0);
        v_gst_pct := COALESCE(v_item.gst_percentage, 0);
        v_igst_pct := COALESCE(v_item.igst_percentage, 0);
        v_lot_no := TRIM(COALESCE(v_item.lot_no, 'LOT-' || to_char((p_invoice->>'date')::DATE, 'YYYYMMDD')));
        v_hsn_sac := TRIM(COALESCE(v_item.hsn_sac, ''));
        v_grade := UPPER(TRIM(COALESCE(v_item.grade, '')));
        v_reorder_level := COALESCE(v_item.reorder_level, 0);
        
        IF v_item.purchase_date IS NOT NULL AND v_item.purchase_date != '' THEN
            v_p_date := (v_item.purchase_date)::DATE;
        ELSE
            v_p_date := (p_invoice->>'date')::DATE;
        END IF;

        IF v_item.expiry_date IS NOT NULL AND v_item.expiry_date != '' THEN
            v_e_date := (v_item.expiry_date)::DATE;
        ELSE
            v_e_date := NULL;
        END IF;

        -- Calculations
        v_gross_amount := ROUND((v_qty * v_unit_price)::NUMERIC, 2);
        v_discount_amount := ROUND((v_gross_amount * (v_disc_pct / 100.0))::NUMERIC, 2);
        v_net_amount := v_gross_amount - v_discount_amount;
        v_item_gst := ROUND((v_net_amount * (v_gst_pct / 100.0))::NUMERIC, 2);
        v_item_igst := ROUND((v_net_amount * (v_igst_pct / 100.0))::NUMERIC, 2);
        v_item_total := v_net_amount + v_item_gst + v_item_igst;

        v_calc_subtotal := v_calc_subtotal + v_net_amount;
        v_calc_gst_total := v_calc_gst_total + v_item_gst;
        v_calc_igst_total := v_calc_igst_total + v_item_igst;

        -- Insert line item
        INSERT INTO invoice_items (
            invoice_id, material, quantity, unit, unit_price,
            discount_percentage, gst_percentage, igst_percentage,
            item_subtotal, item_gst_value, item_igst_value, item_total,
            batch_no, hsn_sac, grade
        ) VALUES (
            v_invoice_id, v_mat_code, v_qty, v_unit, v_unit_price,
            v_disc_pct, v_gst_pct, v_igst_pct,
            v_net_amount, v_item_gst, v_item_igst, v_item_total,
            v_lot_no, v_hsn_sac, v_grade
        );

        -- Update or Insert Material Master (Lock row with FOR UPDATE)
        SELECT EXISTS(
            SELECT 1 FROM materials WHERE material_code = v_mat_code FOR UPDATE
        ) INTO v_lot_exists;

        IF v_lot_exists THEN
            UPDATE materials
            SET description = COALESCE(NULLIF(description, ''), v_mat_name),
                quantity = quantity + v_qty,
                category = COALESCE(NULLIF(category, ''), v_category),
                unit = COALESCE(NULLIF(unit, ''), v_unit),
                reorder_level = CASE WHEN reorder_level > 0 THEN reorder_level ELSE v_reorder_level END,
                unit_price = CASE WHEN v_unit_price > 0 THEN v_unit_price ELSE unit_price END,
                purchase_date = v_p_date,
                expiry_date = COALESCE(v_e_date, expiry_date),
                lot_no = v_lot_no,
                hsn_sac = COALESCE(NULLIF(hsn_sac, ''), v_hsn_sac),
                grade = COALESCE(NULLIF(grade, ''), v_grade),
                last_updated = CURRENT_TIMESTAMP
            WHERE material_code = v_mat_code;
        ELSE
            INSERT INTO materials (
                material_code, description, category, opening_stock,
                quantity, unit, unit_price, purchase_date, expiry_date,
                lot_no, reorder_level, hsn_sac, grade, last_updated
            ) VALUES (
                v_mat_code, v_mat_name, v_category, 0.000,
                v_qty, v_unit, v_unit_price, v_p_date, v_e_date,
                v_lot_no, v_reorder_level, v_hsn_sac, v_grade, CURRENT_TIMESTAMP
            );
        END IF;

        -- Record operational batch in batches table
        INSERT INTO batches (
            batch_no, material_code, description, received_quantity,
            available_quantity, uom, department, received_date, invoice_id
        ) VALUES (
            v_lot_no, v_mat_code, v_mat_name, v_qty,
            v_qty, v_unit, 'General Storage', v_p_date, v_invoice_id
        );
    END LOOP;

    -- Final invoice header update
    v_final_grand_total := ROUND(v_calc_subtotal + v_calc_gst_total + v_calc_igst_total, 2);
    v_final_total := v_final_grand_total + COALESCE((p_invoice->>'round_off_value')::NUMERIC, 0);

    UPDATE invoices
    SET total_excl_tax = v_calc_subtotal,
        total_gst = v_calc_gst_total,
        total_igst = v_calc_igst_total,
        grand_total = v_final_grand_total,
        final_total = v_final_total
    WHERE id = v_invoice_id;

    v_result := jsonb_build_object(
        'success', true,
        'invoice_id', v_invoice_id,
        'subtotal', v_calc_subtotal,
        'total_gst', v_calc_gst_total,
        'total_igst', v_calc_igst_total,
        'grand_total', v_final_grand_total,
        'final_total', v_final_total
    );

    -- Store idempotency result
    IF v_idempotency_key IS NOT NULL AND TRIM(v_idempotency_key) != '' THEN
        INSERT INTO idempotency_keys (idempotency_key, operation_type, user_id, device_id, status, response)
        VALUES (
            v_idempotency_key, 
            'invoice_create', 
            auth.uid(), 
            p_invoice->>'device_id', 
            'completed', 
            v_result
        ) ON CONFLICT (idempotency_key) DO UPDATE SET response = EXCLUDED.response;
    END IF;

    -- Audit log
    INSERT INTO audit_logs (user_id, operation, module, record_id, details)
    VALUES (auth.uid(), 'CREATE', 'invoices', v_invoice_id::TEXT, jsonb_build_object('invoice_no', p_invoice->>'invoice_no', 'grand_total', v_final_grand_total));

    -- Recalculate alerts
    PERFORM generate_inventory_alerts();

    RETURN v_result;
END;
$$;

-- 6.2 CREATE DISPATCH FIFO WITH IDEMPOTENCY
CREATE OR REPLACE FUNCTION create_dispatch_fifo(
    p_dispatch JSONB,
    p_idempotency_key TEXT DEFAULT NULL
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_idempotency_key TEXT;
    v_cached_response JSONB;
    v_dispatch_id BIGINT;
    v_mat_code TEXT;
    v_product_name TEXT;
    v_req_qty NUMERIC(15, 3);
    v_unit TEXT;
    v_location TEXT;
    v_dept TEXT;
    v_date DATE;
    
    v_total_available NUMERIC(15, 3);
    v_remaining_to_dispatch NUMERIC(15, 3);
    v_take NUMERIC(15, 3);
    v_batch RECORD;
    v_allocations JSONB := '[]'::JSONB;
    v_result JSONB;
BEGIN
    v_idempotency_key := COALESCE(p_idempotency_key, p_dispatch->>'idempotency_key');

    -- Idempotency check
    IF v_idempotency_key IS NOT NULL AND TRIM(v_idempotency_key) != '' THEN
        SELECT response INTO v_cached_response 
        FROM idempotency_keys 
        WHERE idempotency_key = v_idempotency_key AND status = 'completed';

        IF v_cached_response IS NOT NULL THEN
            RETURN v_cached_response;
        END IF;
    END IF;

    v_mat_code := TRIM(p_dispatch->>'material_code');
    v_product_name := TRIM(COALESCE(p_dispatch->>'product', v_mat_code));
    v_req_qty := (p_dispatch->>'quantity')::NUMERIC;
    v_unit := TRIM(COALESCE(p_dispatch->>'units', 'kg'));
    v_location := TRIM(COALESCE(p_dispatch->>'location', ''));
    v_dept := TRIM(COALESCE(p_dispatch->>'department', ''));
    v_date := (p_dispatch->>'date')::DATE;

    IF v_req_qty <= 0 THEN
        RAISE EXCEPTION 'Dispatch quantity must be greater than zero.';
    END IF;

    -- Calculate total available stock across active batches
    SELECT COALESCE(SUM(available_quantity), 0)
    INTO v_total_available
    FROM batches
    WHERE (material_code = v_mat_code OR description ILIKE v_product_name)
      AND available_quantity > 0.0001;

    IF v_total_available < v_req_qty THEN
        RAISE EXCEPTION 'Insufficient stock! Requested: %, Available in batches: %', v_req_qty, v_total_available;
    END IF;

    -- Insert Dispatches header record
    INSERT INTO dispatches (
        date, material_code, product, quantity, units, location, department
    ) VALUES (
        v_date, v_mat_code, v_product_name, v_req_qty, v_unit, v_location, v_dept
    ) RETURNING id INTO v_dispatch_id;

    -- FIFO Deduction with FOR UPDATE row locking
    v_remaining_to_dispatch := v_req_qty;

    FOR v_batch IN
        SELECT id, batch_no, available_quantity
        FROM batches
        WHERE (material_code = v_mat_code OR description ILIKE v_product_name)
          AND available_quantity > 0.0001
        ORDER BY id ASC
        FOR UPDATE
    LOOP
        EXIT WHEN v_remaining_to_dispatch <= 0;

        IF v_batch.available_quantity <= v_remaining_to_dispatch THEN
            v_take := v_batch.available_quantity;
            UPDATE batches SET available_quantity = 0 WHERE id = v_batch.id;
            v_remaining_to_dispatch := v_remaining_to_dispatch - v_take;
        ELSE
            v_take := v_remaining_to_dispatch;
            UPDATE batches SET available_quantity = available_quantity - v_take WHERE id = v_batch.id;
            v_remaining_to_dispatch := 0;
        END IF;

        -- Record allocation
        INSERT INTO dispatch_batches (dispatch_id, batch_no, batch_id, quantity)
        VALUES (v_dispatch_id, v_batch.batch_no, v_batch.id, v_take);

        v_allocations := v_allocations || jsonb_build_object(
            'batch_id', v_batch.id,
            'batch_no', v_batch.batch_no,
            'quantity', v_take
        );
    END LOOP;

    -- Synchronize Material Master aggregate stock with FOR UPDATE lock
    UPDATE materials
    SET quantity = GREATEST(0, quantity - v_req_qty),
        last_updated = CURRENT_TIMESTAMP
    WHERE material_code = v_mat_code;

    v_result := jsonb_build_object(
        'success', true,
        'dispatch_id', v_dispatch_id,
        'dispatched_quantity', v_req_qty,
        'allocations', v_allocations
    );

    -- Store idempotency record
    IF v_idempotency_key IS NOT NULL AND TRIM(v_idempotency_key) != '' THEN
        INSERT INTO idempotency_keys (idempotency_key, operation_type, user_id, device_id, status, response)
        VALUES (
            v_idempotency_key, 
            'dispatch_create', 
            auth.uid(), 
            p_dispatch->>'device_id', 
            'completed', 
            v_result
        ) ON CONFLICT (idempotency_key) DO UPDATE SET response = EXCLUDED.response;
    END IF;

    -- Audit log
    INSERT INTO audit_logs (user_id, operation, module, record_id, details)
    VALUES (auth.uid(), 'CREATE', 'dispatches', v_dispatch_id::TEXT, jsonb_build_object('material_code', v_mat_code, 'quantity', v_req_qty));

    -- Recalculate alerts
    PERFORM generate_inventory_alerts();

    RETURN v_result;
END;
$$;

-- 6.3 CREATE TRANSFER WITH IDEMPOTENCY
CREATE OR REPLACE FUNCTION create_transfer(
    p_transfer JSONB,
    p_idempotency_key TEXT DEFAULT NULL
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_idempotency_key TEXT;
    v_cached_response JSONB;
    v_transfer_id BIGINT;
    v_code TEXT;
    v_lot_no TEXT;
    v_desc TEXT;
    v_dept TEXT;
    v_person TEXT;
    v_units TEXT;
    v_date DATE;
    v_outward NUMERIC(15, 3);
    v_return_units NUMERIC(15, 3);
    v_net_change NUMERIC(15, 3);
    
    v_current_stock NUMERIC(15, 3);
    v_remaining_balance NUMERIC(15, 3);
    v_mat_id BIGINT;
    v_result JSONB;
BEGIN
    v_idempotency_key := COALESCE(p_idempotency_key, p_transfer->>'idempotency_key');

    -- Idempotency check
    IF v_idempotency_key IS NOT NULL AND TRIM(v_idempotency_key) != '' THEN
        SELECT response INTO v_cached_response 
        FROM idempotency_keys 
        WHERE idempotency_key = v_idempotency_key AND status = 'completed';

        IF v_cached_response IS NOT NULL THEN
            RETURN v_cached_response;
        END IF;
    END IF;

    v_code := TRIM(p_transfer->>'code');
    v_lot_no := TRIM(COALESCE(p_transfer->>'lot_no', ''));
    v_dept := TRIM(COALESCE(p_transfer->>'department', ''));
    v_person := TRIM(COALESCE(p_transfer->>'person', ''));
    v_units := TRIM(COALESCE(p_transfer->>'units', 'kg'));
    v_date := (p_transfer->>'date')::DATE;
    v_outward := COALESCE((p_transfer->>'outward')::NUMERIC, 0.000);
    v_return_units := COALESCE((p_transfer->>'return_units')::NUMERIC, 0.000);

    -- Find Material Master record with atomic lock
    SELECT id, quantity, description, unit
    INTO v_mat_id, v_current_stock, v_desc, v_units
    FROM materials
    WHERE material_code = v_code
    FOR UPDATE;

    IF v_mat_id IS NULL THEN
        RAISE EXCEPTION 'Material not found in Material Master for code: %', v_code;
    END IF;

    -- Validation
    IF v_outward > v_current_stock THEN
        RAISE EXCEPTION 'Insufficient stock in Material Master! Available: %, Transfer Out: %', v_current_stock, v_outward;
    END IF;

    -- Net Change = Return Quantity - Outward Quantity
    v_net_change := v_return_units - v_outward;
    v_remaining_balance := ROUND(v_current_stock + v_net_change, 3);

    -- Update material stock
    UPDATE materials
    SET quantity = v_remaining_balance,
        last_updated = CURRENT_TIMESTAMP
    WHERE id = v_mat_id;

    -- Save transfer record
    INSERT INTO transfers (
        date, code, description, lot_no, outward, units, department, person, return_units, availability
    ) VALUES (
        v_date, v_code, v_desc, v_lot_no, v_outward, v_units, v_dept, v_person, v_return_units, v_remaining_balance
    ) RETURNING id INTO v_transfer_id;

    v_result := jsonb_build_object(
        'success', true,
        'transfer_id', v_transfer_id,
        'net_change', v_net_change,
        'remaining_balance', v_remaining_balance
    );

    -- Store idempotency
    IF v_idempotency_key IS NOT NULL AND TRIM(v_idempotency_key) != '' THEN
        INSERT INTO idempotency_keys (idempotency_key, operation_type, user_id, device_id, status, response)
        VALUES (
            v_idempotency_key, 
            'transfer_create', 
            auth.uid(), 
            p_transfer->>'device_id', 
            'completed', 
            v_result
        ) ON CONFLICT (idempotency_key) DO UPDATE SET response = EXCLUDED.response;
    END IF;

    -- Audit log
    INSERT INTO audit_logs (user_id, operation, module, record_id, details)
    VALUES (auth.uid(), 'CREATE', 'transfers', v_transfer_id::TEXT, jsonb_build_object('code', v_code, 'outward', v_outward, 'department', v_dept));

    -- Recalculate alerts
    PERFORM generate_inventory_alerts();

    RETURN v_result;
END;
$$;

-- 6.4 CREATE STOCK ADJUSTMENT WITH IDEMPOTENCY
CREATE OR REPLACE FUNCTION create_stock_adjustment(
    p_code TEXT,
    p_operation TEXT,
    p_amount NUMERIC,
    p_reason TEXT,
    p_user TEXT,
    p_idempotency_key TEXT DEFAULT NULL
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_idempotency_key TEXT;
    v_cached_response JSONB;
    v_current_total NUMERIC(15, 3);
    v_new_total NUMERIC(15, 3);
    v_remaining NUMERIC(15, 3);
    v_lot RECORD;
    v_latest_id BIGINT;
    v_op TEXT := LOWER(TRIM(p_operation));
    v_result JSONB;
BEGIN
    v_idempotency_key := p_idempotency_key;

    -- Idempotency check
    IF v_idempotency_key IS NOT NULL AND TRIM(v_idempotency_key) != '' THEN
        SELECT response INTO v_cached_response 
        FROM idempotency_keys 
        WHERE idempotency_key = v_idempotency_key AND status = 'completed';

        IF v_cached_response IS NOT NULL THEN
            RETURN v_cached_response;
        END IF;
    END IF;

    IF p_amount <= 0 THEN
        RAISE EXCEPTION 'Adjustment amount must be positive.';
    END IF;

    SELECT COALESCE(SUM(quantity), 0)
    INTO v_current_total
    FROM materials
    WHERE material_code = p_code;

    IF v_op = 'subtract' THEN
        IF p_amount > v_current_total THEN
            RAISE EXCEPTION 'Cannot subtract % — only % in stock for %', p_amount, v_current_total, p_code;
        END IF;

        -- Consume FIFO from oldest lots first with FOR UPDATE
        v_remaining := p_amount;
        FOR v_lot IN
            SELECT id, quantity
            FROM materials
            WHERE material_code = p_code AND quantity > 0
            ORDER BY id ASC
            FOR UPDATE
        LOOP
            EXIT WHEN v_remaining <= 0;

            IF v_lot.quantity <= v_remaining THEN
                UPDATE materials SET quantity = 0, last_updated = CURRENT_TIMESTAMP WHERE id = v_lot.id;
                v_remaining := v_remaining - v_lot.quantity;
            ELSE
                UPDATE materials SET quantity = quantity - v_remaining, last_updated = CURRENT_TIMESTAMP WHERE id = v_lot.id;
                v_remaining := 0;
            END IF;
        END LOOP;

        v_new_total := v_current_total - p_amount;
    ELSE
        -- Add: target latest lot or create default
        SELECT id INTO v_latest_id
        FROM materials
        WHERE material_code = p_code
        ORDER BY id DESC
        LIMIT 1;

        IF v_latest_id IS NOT NULL THEN
            UPDATE materials
            SET quantity = quantity + p_amount,
                last_updated = CURRENT_TIMESTAMP
            WHERE id = v_latest_id;
        ELSE
            INSERT INTO materials (
                material_code, description, category, quantity, opening_stock, unit, last_updated
            ) VALUES (
                p_code, 'Material ' || p_code, 'General', p_amount, p_amount, 'kg', CURRENT_TIMESTAMP
            );
        END IF;

        v_new_total := v_current_total + p_amount;
    END IF;

    -- Record audit log in stock_adjustments
    INSERT INTO stock_adjustments (
        material_code, operation, amount, reason, before_qty, after_qty, adjusted_by
    ) VALUES (
        p_code, p_operation, p_amount, p_reason, v_current_total, v_new_total, p_user
    );

    v_result := jsonb_build_object(
        'success', true,
        'material_code', p_code,
        'before_qty', v_current_total,
        'after_qty', v_new_total
    );

    -- Store idempotency
    IF v_idempotency_key IS NOT NULL AND TRIM(v_idempotency_key) != '' THEN
        INSERT INTO idempotency_keys (idempotency_key, operation_type, user_id, device_id, status, response)
        VALUES (
            v_idempotency_key, 
            'stock_adjustment_create', 
            auth.uid(), 
            NULL, 
            'completed', 
            v_result
        ) ON CONFLICT (idempotency_key) DO UPDATE SET response = EXCLUDED.response;
    END IF;

    -- Recalculate alerts
    PERFORM generate_inventory_alerts();

    RETURN v_result;
END;
$$;

-- ----------------------------------------------------------------------------
-- 7. RLS POLICIES FOR NEW TABLES
-- ----------------------------------------------------------------------------
ALTER TABLE idempotency_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- idempotency_keys
DROP POLICY IF EXISTS "Allow all authenticated to read/write idempotency_keys" ON idempotency_keys;
CREATE POLICY "Allow all authenticated to read/write idempotency_keys"
ON idempotency_keys FOR ALL TO authenticated, anon USING (true) WITH CHECK (true);

-- user_profiles
DROP POLICY IF EXISTS "Allow authenticated to view user_profiles" ON user_profiles;
CREATE POLICY "Allow authenticated to view user_profiles"
ON user_profiles FOR SELECT TO authenticated, anon USING (true);

DROP POLICY IF EXISTS "Allow authenticated to update own profile" ON user_profiles;
CREATE POLICY "Allow authenticated to update own profile"
ON user_profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- audit_logs
DROP POLICY IF EXISTS "Allow authenticated to insert and view audit_logs" ON audit_logs;
CREATE POLICY "Allow authenticated to insert and view audit_logs"
ON audit_logs FOR ALL TO authenticated, anon USING (true) WITH CHECK (true);

-- notifications
DROP POLICY IF EXISTS "Allow authenticated to view notifications" ON notifications;
CREATE POLICY "Allow authenticated to view notifications"
ON notifications FOR SELECT TO authenticated, anon USING (true);

DROP POLICY IF EXISTS "Allow authenticated to update notifications (e.g. mark as read)" ON notifications;
CREATE POLICY "Allow authenticated to update notifications (e.g. mark as read)"
ON notifications FOR UPDATE TO authenticated, anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated to insert notifications" ON notifications;
CREATE POLICY "Allow authenticated to insert notifications"
ON notifications FOR INSERT TO authenticated, anon WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated to delete notifications" ON notifications;
CREATE POLICY "Allow authenticated to delete notifications"
ON notifications FOR DELETE TO authenticated, anon USING (true);

-- ----------------------------------------------------------------------------
-- 8. REALTIME REPLICA IDENTITY & PUBLICATION SETUP
-- ----------------------------------------------------------------------------
ALTER TABLE materials REPLICA IDENTITY FULL;
ALTER TABLE batches REPLICA IDENTITY FULL;
ALTER TABLE dispatches REPLICA IDENTITY FULL;
ALTER TABLE dispatch_batches REPLICA IDENTITY FULL;
ALTER TABLE transfers REPLICA IDENTITY FULL;
ALTER TABLE invoices REPLICA IDENTITY FULL;
ALTER TABLE invoice_items REPLICA IDENTITY FULL;
ALTER TABLE stock_adjustments REPLICA IDENTITY FULL;
ALTER TABLE vendors REPLICA IDENTITY FULL;
ALTER TABLE category_locations REPLICA IDENTITY FULL;
ALTER TABLE notifications REPLICA IDENTITY FULL;
ALTER TABLE user_profiles REPLICA IDENTITY FULL;

DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE materials;
EXCEPTION WHEN OTHERS THEN NULL;
END;
$$;

DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE batches;
EXCEPTION WHEN OTHERS THEN NULL;
END;
$$;

DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE dispatches;
EXCEPTION WHEN OTHERS THEN NULL;
END;
$$;

DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE dispatch_batches;
EXCEPTION WHEN OTHERS THEN NULL;
END;
$$;

DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE transfers;
EXCEPTION WHEN OTHERS THEN NULL;
END;
$$;

DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE invoices;
EXCEPTION WHEN OTHERS THEN NULL;
END;
$$;

DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE invoice_items;
EXCEPTION WHEN OTHERS THEN NULL;
END;
$$;

DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE stock_adjustments;
EXCEPTION WHEN OTHERS THEN NULL;
END;
$$;

DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE vendors;
EXCEPTION WHEN OTHERS THEN NULL;
END;
$$;

DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE category_locations;
EXCEPTION WHEN OTHERS THEN NULL;
END;
$$;

DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE notifications;
EXCEPTION WHEN OTHERS THEN NULL;
END;
$$;

DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE user_profiles;
EXCEPTION WHEN OTHERS THEN NULL;
END;
$$;

-- Trigger initial alert check
SELECT generate_inventory_alerts();
