-- ============================================================================
-- BENCHMARK MATERIAL MANAGEMENT SYSTEM (BENCHMARK MMS)
-- PostgreSQL Database Schema for Supabase
-- ============================================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ----------------------------------------------------------------------------
-- 1. MATERIALS TABLE
-- Supports lot-level tracking. Note: material_code is NOT unique because a single
-- material code can have multiple batches/lots.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_code TEXT NOT NULL,
    description TEXT,
    category TEXT,
    opening_stock NUMERIC(15, 3) NOT NULL DEFAULT 0.000,
    quantity NUMERIC(15, 3) NOT NULL DEFAULT 0.000,
    reorder_level NUMERIC(15, 3) NOT NULL DEFAULT 0.000,
    purchase_date DATE,
    expiry_date DATE,
    lot_no TEXT,
    unit_price NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    unit TEXT NOT NULL DEFAULT 'kg',
    last_updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hsn_sac TEXT,
    grade TEXT
);

CREATE INDEX IF NOT EXISTS idx_materials_code ON materials(material_code);
CREATE INDEX IF NOT EXISTS idx_materials_category ON materials(category);
CREATE INDEX IF NOT EXISTS idx_materials_quantity ON materials(quantity);
CREATE INDEX IF NOT EXISTS idx_materials_code_lot ON materials(material_code, lot_no);
CREATE INDEX IF NOT EXISTS idx_materials_expiry ON materials(expiry_date);

-- ----------------------------------------------------------------------------
-- 2. VENDORS TABLE
-- Supplier directory with tax and contact details
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS vendors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contact TEXT,
    place TEXT,
    pincode TEXT,
    gstin TEXT,
    material TEXT,
    info TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_vendors_name ON vendors(name);

-- ----------------------------------------------------------------------------
-- 3. INVOICES TABLE
-- Inward purchase invoices header
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id TEXT,
    date DATE NOT NULL,
    invoice_no TEXT NOT NULL UNIQUE,
    vendor TEXT,
    no_of_items INT NOT NULL DEFAULT 1,
    total_excl_tax NUMERIC(18, 4) NOT NULL DEFAULT 0.00,
    total_gst NUMERIC(18, 4) NOT NULL DEFAULT 0.00,
    total_igst NUMERIC(18, 4) NOT NULL DEFAULT 0.00,
    cgst_percent NUMERIC(18, 4) NOT NULL DEFAULT 0.00,
    sgst_percent NUMERIC(18, 4) NOT NULL DEFAULT 0.00,
    round_off_value NUMERIC(18, 4) NOT NULL DEFAULT 0.00,
    grand_total NUMERIC(18, 4) NOT NULL DEFAULT 0.00,
    final_total NUMERIC(18, 4) NOT NULL DEFAULT 0.00,
    payment_status TEXT NOT NULL DEFAULT 'Pending' CHECK (payment_status IN ('Pending', 'Paid', 'Partially Paid', 'Cancelled')),
    remarks TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_invoices_no ON invoices(invoice_no);
CREATE INDEX IF NOT EXISTS idx_invoices_date ON invoices(date);
CREATE INDEX IF NOT EXISTS idx_invoices_vendor ON invoices(vendor);

-- ----------------------------------------------------------------------------
-- 4. INVOICE ITEMS TABLE
-- Line items belonging to invoices with tax, discount, lot and HSN details
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS invoice_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    material TEXT NOT NULL,
    quantity NUMERIC(15, 3) NOT NULL CHECK (quantity >= 0),
    unit TEXT NOT NULL DEFAULT 'kg',
    unit_price NUMERIC(18, 4) NOT NULL DEFAULT 0.00,
    discount_percentage NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    gst_percentage NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    igst_percentage NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    item_subtotal NUMERIC(18, 4) NOT NULL DEFAULT 0.00,
    item_gst_value NUMERIC(18, 4) NOT NULL DEFAULT 0.00,
    item_igst_value NUMERIC(18, 4) NOT NULL DEFAULT 0.00,
    item_total NUMERIC(18, 4) NOT NULL DEFAULT 0.00,
    batch_no TEXT,
    hsn_sac TEXT,
    grade TEXT
);

CREATE INDEX IF NOT EXISTS idx_invoice_items_invoice ON invoice_items(invoice_id);
CREATE INDEX IF NOT EXISTS idx_invoice_items_material ON invoice_items(material);

-- ----------------------------------------------------------------------------
-- 5. BATCHES TABLE (Storage & Batch Management)
-- Tracks active batches and inward storage
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_no TEXT NOT NULL,
    material_code TEXT,
    description TEXT,
    received_quantity NUMERIC(15, 3) NOT NULL CHECK (received_quantity >= 0),
    available_quantity NUMERIC(15, 3) NOT NULL CHECK (available_quantity >= 0),
    uom TEXT NOT NULL DEFAULT 'kg',
    department TEXT,
    received_date DATE,
    invoice_id BIGINT REFERENCES invoices(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_batches_code ON batches(material_code);
CREATE INDEX IF NOT EXISTS idx_batches_avail ON batches(available_quantity);
CREATE INDEX IF NOT EXISTS idx_batches_date ON batches(received_date);
CREATE INDEX IF NOT EXISTS idx_batches_desc ON batches(description);

-- ----------------------------------------------------------------------------
-- 6. DISPATCHES TABLE
-- Outward finished product dispatch records
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dispatches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    material_code TEXT NOT NULL,
    product TEXT,
    quantity NUMERIC(15, 3) NOT NULL CHECK (quantity > 0),
    units TEXT NOT NULL DEFAULT 'kg',
    location TEXT,
    department TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_dispatches_code ON dispatches(material_code);
CREATE INDEX IF NOT EXISTS idx_dispatches_date ON dispatches(date);

-- ----------------------------------------------------------------------------
-- 7. DISPATCH BATCHES TABLE
-- Exact FIFO allocations from batches consumed for each dispatch
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dispatch_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispatch_id BIGINT NOT NULL REFERENCES dispatches(id) ON DELETE CASCADE,
    batch_no TEXT NOT NULL,
    batch_id BIGINT NOT NULL REFERENCES batches(id) ON DELETE RESTRICT,
    quantity NUMERIC(15, 3) NOT NULL CHECK (quantity > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_dispatch_batches_dispatch ON dispatch_batches(dispatch_id);
CREATE INDEX IF NOT EXISTS idx_dispatch_batches_batch ON dispatch_batches(batch_id);

-- ----------------------------------------------------------------------------
-- 8. TRANSFERS TABLE
-- Department transfers & returns with net change and stock balance
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    code TEXT NOT NULL,
    description TEXT,
    lot_no TEXT,
    outward NUMERIC(15, 3) NOT NULL DEFAULT 0.000 CHECK (outward >= 0),
    units TEXT NOT NULL DEFAULT 'kg',
    department TEXT,
    person TEXT,
    return_units NUMERIC(15, 3) NOT NULL DEFAULT 0.000 CHECK (return_units >= 0),
    availability NUMERIC(15, 3) NOT NULL DEFAULT 0.000,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_transfers_code ON transfers(code);
CREATE INDEX IF NOT EXISTS idx_transfers_date ON transfers(date);
CREATE INDEX IF NOT EXISTS idx_transfers_dept ON transfers(department);

-- ----------------------------------------------------------------------------
-- 9. STOCK ADJUSTMENTS TABLE
-- Secure auditable adjustments (Add / Subtract / Set / Sub)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS stock_adjustments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_code TEXT NOT NULL,
    operation TEXT NOT NULL,
    amount NUMERIC(15, 3) NOT NULL,
    reason TEXT,
    before_qty NUMERIC(15, 3) NOT NULL,
    after_qty NUMERIC(15, 3) NOT NULL,
    adjusted_by TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_stock_adj_code ON stock_adjustments(material_code);
CREATE INDEX IF NOT EXISTS idx_stock_adj_created ON stock_adjustments(created_at);

-- ----------------------------------------------------------------------------
-- 10. CATEGORY SHELF LOCATIONS TABLE
-- Maps categories to physical warehouse racks / shelves / bins
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS category_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL UNIQUE,
    location TEXT,
    last_updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_category_loc_category ON category_locations(category);

-- ----------------------------------------------------------------------------
-- 11. SYSTEM SETTINGS TABLE
-- For application config (e.g. security passwords, factory info, mailer config)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS system_settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
